# Generated by Django 4.0.3 on 2022-03-25 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=44)),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
