# Generated by Django 4.0.3 on 2022-03-25 00:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('products', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.sale')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
