# Generated by Django 4.0.3 on 2022-03-25 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dicount_percentage', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('initial_datetime', models.DateTimeField()),
                ('final_datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
