# Generated by Django 4.0.3 on 2022-03-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='dicount_percentage',
            new_name='discount_percentage',
        ),
    ]
