# Generated by Django 4.0.3 on 2022-03-25 00:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('category', '0001_initial'),
        ('course_link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price_client', models.FloatField()),
                ('price_seller', models.FloatField()),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiration_date', models.DateField()),
                ('categories', models.ManyToManyField(related_name='categories', to='category.category')),
                ('course_links', models.ManyToManyField(related_name='course_links', to='course_link.courselink')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
